# Generated by Django 5.1.15 on 2026-08-05 20:19

import communications.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_academicyear_academicterm_classroom_academic_year_and_more'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('communication_type', models.CharField(choices=[('announcement', 'Announcement'), ('notice', 'Notice'), ('reminder', 'Reminder'), ('emergency', 'Emergency'), ('academic', 'Academic'), ('finance', 'Finance'), ('attendance', 'Attendance'), ('timetable', 'Timetable'), ('event', 'Event'), ('general', 'General')], default='general', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending approval'), ('scheduled', 'Scheduled'), ('publishing', 'Publishing'), ('published', 'Published'), ('partially_delivered', 'Partially delivered'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=25)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('audience_type', models.CharField(choices=[('school', 'Entire school'), ('all_students', 'All students'), ('all_guardians', 'All guardians'), ('all_teachers', 'All teachers'), ('all_admins', 'All administrators'), ('all_accountants', 'All accountants'), ('classrooms', 'Selected classrooms'), ('users', 'Selected users')], max_length=20)),
                ('include_guardians_of_targets', models.BooleanField(default=False, help_text='When targeting students (directly or via classrooms), also notify their linked guardians.')),
                ('channels', models.JSONField(default=list, help_text="Delivery channels requested, e.g. ['in_app', 'email'].")),
                ('allow_replies', models.BooleanField(default=False)),
                ('requires_acknowledgement', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communications_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='schools.school')),
                ('target_classrooms', models.ManyToManyField(blank=True, related_name='targeted_communications', to='academics.classroom')),
                ('target_users', models.ManyToManyField(blank=True, related_name='targeted_communications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=communications.models.communication_attachment_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'png', 'jpg', 'jpeg'])])),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='communications.communication')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('in_app', 'In-app'), ('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('read', 'Read'), ('acknowledged', 'Acknowledged')], db_index=True, default='pending', max_length=15)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('provider_message_id', models.CharField(blank=True, max_length=100)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='communications.communication')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-communication_id', 'recipient_id'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('fee_reminder', 'Fee reminder'), ('attendance_alert', 'Attendance alert'), ('timetable_change', 'Timetable change'), ('exam_reminder', 'Examination reminder'), ('school_closure', 'School closure'), ('meeting', 'Meeting'), ('report_available', 'Report availability'), ('certificate_available', 'Certificate availability'), ('disciplinary', 'Disciplinary notice'), ('emergency', 'Emergency notice'), ('general', 'General announcement')], max_length=30)),
                ('subject_template', models.CharField(max_length=200)),
                ('body_template', models.TextField()),
                ('allowed_variables', models.JSONField(blank=True, default=list)),
                ('channel', models.CharField(choices=[('in_app', 'In-app'), ('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='in_app', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_templates_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_templates', to='schools.school')),
            ],
            options={
                'ordering': ['school', 'category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('whatsapp_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('digest_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['school', 'status', 'created_at'], name='communicati_school__e54f35_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['school', 'scheduled_at'], name='communicati_school__3cabd5_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationrecipient',
            index=models.Index(fields=['recipient', 'read_at'], name='communicati_recipie_864c8c_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationrecipient',
            index=models.Index(fields=['recipient', 'status'], name='communicati_recipie_985836_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationrecipient',
            index=models.Index(fields=['communication', 'recipient'], name='communicati_communi_0e7593_idx'),
        ),
        migrations.AddConstraint(
            model_name='communicationrecipient',
            constraint=models.UniqueConstraint(fields=('communication', 'recipient', 'channel'), name='unique_delivery_per_communication_recipient_channel'),
        ),
        migrations.AddConstraint(
            model_name='communicationrecipient',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_count__gte', 0)), name='communication_recipient_attempt_count_non_negative'),
        ),
        migrations.AddIndex(
            model_name='communicationtemplate',
            index=models.Index(fields=['school', 'category', 'is_active'], name='communicati_school__027ebc_idx'),
        ),
        migrations.AddConstraint(
            model_name='communicationtemplate',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_template_name_per_school'),
        ),
    ]
