# Generated by Django 5.2.16 on 2026-08-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communication",
            name="channels",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Delivery channels requested, e.g. ['in_app', 'email'].",
            ),
        ),
    ]
