# Generated by Django 5.2.16 on 2026-07-20 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="financialtransaction",
            options={
                "ordering": ["-created_at", "-pk"],
                "verbose_name": "Financial Transaction",
                "verbose_name_plural": "Financial Transactions",
            },
        ),
    ]
