# Generated by Django 5.1.15 on 2026-07-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="guardianstudentlink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary_guardian", True)),
                fields=("student",),
                name="one_primary_guardian_per_student",
            ),
        ),
    ]
