# Generated by Django 5.2.16 on 2026-07-20 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_guardianstudentlink_one_primary_guardian_per_student"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accesscode",
            options={"ordering": ["-created_at", "-pk"]},
        ),
    ]
