# Generated by Django 5.2.16 on 2026-08-01 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateNumberSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                (
                    "certificate_type",
                    models.CharField(
                        choices=[
                            ("COMPLETION", "Certificate of Completion"),
                            ("PARTICIPATION", "Certificate of Participation"),
                            ("GRADUATION", "Graduation Certificate"),
                            ("TESTIMONIAL", "Testimonial"),
                        ],
                        max_length=20,
                    ),
                ),
                ("last_number", models.PositiveBigIntegerField(default=0)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("school", "year", "certificate_type"),
                        name="unique_certificate_number_sequence",
                    )
                ],
            },
        ),
    ]
