# Generated by Django 5.1.15 on 2026-08-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_certificatenumbersequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='branding',
            field=models.JSONField(blank=True, default=dict, help_text='Branding configuration for this certificate template: logo, colors, motto, letterhead/background/watermark images, font family, and security microtext. Falls back to sensible defaults when a field is not configured.'),
        ),
    ]
