# Generated by Django 5.2.16 on 2026-07-20 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grading", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="grade",
            options={"ordering": ["-created_at", "-pk"]},
        ),
        migrations.AlterModelOptions(
            name="subjectgradeapproval",
            options={"ordering": ["-created_at", "-pk"]},
        ),
    ]
