# Generated by Django 5.1.15 on 2026-08-07 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0002_alter_grade_options_and_more'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False, help_text='Indicates the scale currently used for this school.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_scales', to='schools.school')),
            ],
            options={
                'ordering': ['school', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GradeBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_symbol', models.CharField(max_length=10)),
                ('min_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade_point', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('remark', models.CharField(blank=True, max_length=100)),
                ('is_passing', models.BooleanField(default=True)),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boundaries', to='grading.gradingscale')),
            ],
            options={
                'ordering': ['-min_percentage'],
            },
        ),
        migrations.AddConstraint(
            model_name='gradingscale',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='uniq_gradingscale_school_name'),
        ),
        migrations.AddConstraint(
            model_name='gradingscale',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('school',), name='one_active_gradingscale_per_school'),
        ),
        migrations.AddConstraint(
            model_name='gradeboundary',
            constraint=models.UniqueConstraint(fields=('scale', 'grade_symbol'), name='uniq_gradeboundary_scale_symbol'),
        ),
    ]
