# Generated by Django 5.1.15 on 2026-07-14 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=30)),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        help_text="For example: S1, S4, S5 or Year 1.",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classrooms",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "ordering": ["school", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("school", "code"),
                        name="unique_classroom_code_per_school",
                    )
                ],
            },
        ),
    ]
