# Generated by Django 5.1.15 on 2026-07-17 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_guardianstudentlink_one_primary_guardian_per_student"),
        ("schools", "0001_initial"),
        ("timetable", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("excused", "Excused"),
                        ],
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "remarks",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Remarks"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "marked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marked_attendance_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Marked By",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="schools.school",
                        verbose_name="School",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="accounts.studentprofile",
                        verbose_name="Student",
                    ),
                ),
                (
                    "timetable_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_records",
                        to="timetable.timetableentry",
                        verbose_name="Timetable Entry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Record",
                "verbose_name_plural": "Attendance Records",
                "ordering": ["-date", "student", "timetable_entry"],
                "indexes": [
                    models.Index(
                        fields=["school", "date"], name="attendance__school__8edf1d_idx"
                    ),
                    models.Index(
                        fields=["student", "date"],
                        name="attendance__student_588cfe_idx",
                    ),
                    models.Index(
                        fields=["timetable_entry", "date"],
                        name="attendance__timetab_a50c6f_idx",
                    ),
                    models.Index(
                        fields=["marked_by", "date"],
                        name="attendance__marked__7b2ef6_idx",
                    ),
                    models.Index(
                        fields=["school", "status"],
                        name="attendance__school__4c88c2_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("student", "timetable_entry", "date"),
                        name="unique_active_student_timetable_entry_date",
                    )
                ],
            },
        ),
    ]
